name: Build and release

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore:
      - .github/**

jobs:
  set-tag-values:
    runs-on: ubuntu-latest
    outputs:
      tag_main: ${{ steps.create_tag.outputs.main }}
      tag_patch: ${{ steps.create_tag.outputs.main }}.${{ github.run_number }}
    steps:
      - id: create_tag
        run: echo "main=$(date +'%Y%m')" >> "$GITHUB_OUTPUT"
  build:
    needs: set-tag-values
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/php-ci@sha256:58b7be780fb1e0bba5a40c12ee4937e5e7da778065b30d2f5113c3445a83967f
    name: Checkout & build Phar
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Full Composer Install
        run: |
          composer update
          composer install
      - name: Validate Code
        run: composer code:lint
      - name: Phar Build
        run: |
          mkdir $HOME/box
          composer require humbug/box --working-dir=$HOME/box
          export PATH=~/box/vendor/bin:$PATH
          composer phar:build
      - uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af
        with:
          artifacts: "terminus.phar"
          tag: ${{needs.set-tag-values.outputs.tag_patch}}
