name: Build and release

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore:
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/php-ci:v8.2
    name: Checkout & build Phar
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Full Composer Install
        run: |
          sudo pecl install pcov
          touch /etc/php/8.3/cli/conf.d/20-pcov.ini
          composer update
          composer install
      - name: Validate Code
        run: composer code:lint
      - name: Phar Build
        run: |
          mkdir $HOME/box
          composer require humbug/box --working-dir=$HOME/box
          export PATH=~/box/vendor/bin:$PATH
          composer phar:build
      - name: Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        if: github.ref_type == 'tag'
        with:
          files: terminus.phar
